/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void panel1_Click1(GPanel source, GEvent event) { //_CODE_:panel1:759483:
  println("panel1 - GPanel >> GEvent." + event + " @ " + millis());
} //_CODE_:panel1:759483:

public void obs_ray_slider_change(GCustomSlider source, GEvent event) { //_CODE_:obs_ray_slider:411017:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
  targetR = source.getValueI();
} //_CODE_:obs_ray_slider:411017:

public void posx_slider_change(GCustomSlider source, GEvent event) { //_CODE_:posx_slider:523357:
  println("custom_slider2 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:posx_slider:523357:

public void posy_slider_change(GCustomSlider source, GEvent event) { //_CODE_:posy_slider:934849:
  println("custom_slider2 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:posy_slider:934849:

public void start_btn_click(GButton source, GEvent event) { //_CODE_:start_btn:575990:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:start_btn:575990:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  panel1 = new GPanel(this, 1184, 45, 600, 495, "Setup");
  panel1.setCollapsible(false);
  panel1.setDraggable(false);
  panel1.setText("Setup");
  panel1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  panel1.setOpaque(true);
  panel1.addEventHandler(this, "panel1_Click1");
  obs_ray_slider = new GCustomSlider(this, 25, 97, 550, 80, "green_red20px");
  obs_ray_slider.setShowValue(true);
  obs_ray_slider.setShowLimits(true);
  obs_ray_slider.setTextOrientation(G4P.ORIENT_RIGHT);
  obs_ray_slider.setLimits(30, 30, 200);
  obs_ray_slider.setNbrTicks(10);
  obs_ray_slider.setStickToTicks(true);
  obs_ray_slider.setShowTicks(true);
  obs_ray_slider.setEasing(30.0);
  obs_ray_slider.setNumberFormat(G4P.INTEGER, 0);
  obs_ray_slider.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  obs_ray_slider.setOpaque(true);
  obs_ray_slider.addEventHandler(this, "obs_ray_slider_change");
  label1 = new GLabel(this, 25, 39, 550, 50);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Raggio Ostacolo");
  label1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  label1.setOpaque(true);
  label2 = new GLabel(this, 25, 193, 550, 50);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Posizione Robot");
  label2.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  label2.setOpaque(true);
  posx_slider = new GCustomSlider(this, 143, 247, 431, 80, "green_red20px");
  posx_slider.setShowValue(true);
  posx_slider.setShowLimits(true);
  posx_slider.setLimits(1, 0, 1);
  posx_slider.setNbrTicks(5);
  posx_slider.setShowTicks(true);
  posx_slider.setNumberFormat(G4P.INTEGER, 0);
  posx_slider.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  posx_slider.setOpaque(true);
  posx_slider.addEventHandler(this, "posx_slider_change");
  label3 = new GLabel(this, 25, 247, 108, 80);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Pos X");
  label3.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  label3.setOpaque(true);
  label4 = new GLabel(this, 25, 330, 108, 80);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Pos Y");
  label4.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  label4.setOpaque(true);
  posy_slider = new GCustomSlider(this, 142, 330, 431, 80, "green_red20px");
  posy_slider.setShowValue(true);
  posy_slider.setShowLimits(true);
  posy_slider.setLimits(1, 0, 1);
  posy_slider.setShowTicks(true);
  posy_slider.setNumberFormat(G4P.INTEGER, 0);
  posy_slider.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  posy_slider.setOpaque(true);
  posy_slider.addEventHandler(this, "posy_slider_change");
  start_btn = new GButton(this, 25, 421, 550, 50);
  start_btn.setText("Avvia Gioco");
  start_btn.addEventHandler(this, "start_btn_click");
  panel1.addControl(obs_ray_slider);
  panel1.addControl(label1);
  panel1.addControl(label2);
  panel1.addControl(posx_slider);
  panel1.addControl(label3);
  panel1.addControl(label4);
  panel1.addControl(posy_slider);
  panel1.addControl(start_btn);
}

// Variable declarations 
// autogenerated do not edit
GPanel panel1; 
GCustomSlider obs_ray_slider; 
GLabel label1; 
GLabel label2; 
GCustomSlider posx_slider; 
GLabel label3; 
GLabel label4; 
GCustomSlider posy_slider; 
GButton start_btn; 
